### Pools Count
http://localhost:5000/pools/count

### Users Count
http://localhost:5000/users/count

### Bets Count
http://localhost:5000/bets/count

### User me
http://localhost:5000/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRW1pbGlvIFNjb2RlbGVyIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUxtNXd1MmdJNk00LTlNcDgxckluM0syMlNMamMyel9mWlBVTi1VNXphd009czk2LWMiLCJzdWIiOiJjbGEydG02dTcwMDAweTc1bWhmaHJiN3VvIiwiaWF0IjoxNjY3NTg1OTQ1LCJleHAiOjE2Njc2NzIzNDV9.Yg9yIJ2yjNG4mSnzJAgd4wOmmll7AXvlhLwG_FVD-Pk

### Create Pool
POST http://localhost:5000/pools HTTP/1.1
content-type: application/json

{
    "title": "Segundo Bolão"
}

### Join Pool
POST http://localhost:5000/pools/JUVXBS/join HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRW1pbGlvIFNjb2RlbGVyIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUxtNXd1MmdJNk00LTlNcDgxckluM0syMlNMamMyel9mWlBVTi1VNXphd009czk2LWMiLCJzdWIiOiJjbGEydG02dTcwMDAweTc1bWhmaHJiN3VvIiwiaWF0IjoxNjY3NTg1OTQ1LCJleHAiOjE2Njc2NzIzNDV9.Yg9yIJ2yjNG4mSnzJAgd4wOmmll7AXvlhLwG_FVD-Pk

### List Pools
GET http://localhost:5000/pools HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRW1pbGlvIFNjb2RlbGVyIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUxtNXd1MmdJNk00LTlNcDgxckluM0syMlNMamMyel9mWlBVTi1VNXphd009czk2LWMiLCJzdWIiOiJjbGEydG02dTcwMDAweTc1bWhmaHJiN3VvIiwiaWF0IjoxNjY3NTg1OTQ1LCJleHAiOjE2Njc2NzIzNDV9.Yg9yIJ2yjNG4mSnzJAgd4wOmmll7AXvlhLwG_FVD-Pk

### Find Pool by Id
GET http://localhost:5000/pools/cla1b2qe2000ay7ll86bnzmtt HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRW1pbGlvIFNjb2RlbGVyIiwiYXZhdGFyVXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUxtNXd1MmdJNk00LTlNcDgxckluM0syMlNMamMyel9mWlBVTi1VNXphd009czk2LWMiLCJzdWIiOiJjbGEydG02dTcwMDAweTc1bWhmaHJiN3VvIiwiaWF0IjoxNjY3NTg1OTQ1LCJleHAiOjE2Njc2NzIzNDV9.Yg9yIJ2yjNG4mSnzJAgd4wOmmll7AXvlhLwG_FVD-Pk

### SignIn
POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
    "access_token": "ya29.a0AeTM1icPqvXNklzoeTVWyCKvOv92VfoduQO8NMOcsxXVTaexJk7RhhuHAnF0Ro3QsZ3Cgq9Ks7p9xc6CDtlwX3u_H-fHD4_oNfnwdiTFVNIWfwHlSkwY553Z6JjGt0qf46jN4tUdoEcKnTY7Ny5RRrqGsJUERwaCgYKAYcSARISFQHWtWOmqdYO6qvhUyfmD4MKm0Vo_w0165"
}